# Docker Compose for development with live reload
version: '3.8'

services:
  # Development environment with live reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: forgejo-integration-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: npm run watch
    networks:
      - dev

  # Build service for creating production assets
  build:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: forgejo-integration-build
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: npm run build
    networks:
      - dev

volumes:
  node_modules:

networks:
  dev:
    driver: bridge
